// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_NBRRTQ5u3l8IsGOTxbGpKY_9MnFXfZQ',
    appId: '1:322637204361:web:841ddbd07752248925ef58',
    messagingSenderId: '322637204361',
    projectId: 'login-32ea3',
    authDomain: 'login-32ea3.firebaseapp.com',
    storageBucket: 'login-32ea3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtC1w1LaZIirMmNmhqHpcoi6KU1xg8dVs',
    appId: '1:322637204361:android:60ff0b464673ae0225ef58',
    messagingSenderId: '322637204361',
    projectId: 'login-32ea3',
    storageBucket: 'login-32ea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrLXQPI37BhGj-96774TpXGGYB2u28M3E',
    appId: '1:322637204361:ios:6b2c9b186de7d9d825ef58',
    messagingSenderId: '322637204361',
    projectId: 'login-32ea3',
    storageBucket: 'login-32ea3.appspot.com',
    iosBundleId: 'com.example.ietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrLXQPI37BhGj-96774TpXGGYB2u28M3E',
    appId: '1:322637204361:ios:6b59d03ccf78028625ef58',
    messagingSenderId: '322637204361',
    projectId: 'login-32ea3',
    storageBucket: 'login-32ea3.appspot.com',
    iosBundleId: 'com.example.ietApp.RunnerTests',
  );
}
